name: Auto-update pull request

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    paths:
      - '.github/workflows/auto-update.yml'

jobs:
  autoupdate:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        target: [roswell, sbcl, ccl]
    steps:
      - uses: actions/checkout@v2
      - name: Auto-update
        run: |
          ./update.sh ${{ matrix.target }} > new-versions
          ./generate-readme.sh ${{ matrix.target }} > ${{ matrix.target }}/README.md
      - name: Versions
        id: versions
        run: |
          echo "::set-output name=list::$(cat new-versions | cut -d , -f 1 | sed -e 's/^/* /')"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Auto-update ${{ matrix.target }}.
          title: Auto-update ${{ matrix.target }}
          body: |
            ### New versions
            ${{ steps.versions.outputs.list }}

            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request).
          labels: auto-update
          branch: auto-update
          branch-suffix: timestamp
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
