name: Build Docker images

on:
  push:
    paths:
      - '**/*/Dockerfile'
      - '**/*/Dockerfile.edge'
      - '**/versions'
      - '.github/workflows/build-images.yml'

jobs:
  roswell:
    name: Roswell
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        target: [debian, ubuntu, alpine]
        version: ["19.05.10.99", "19.06.10.100", "19.08.10.101", "19.09.12.102", "19.12.13.103", "edge"]

    steps:
      - uses: actions/checkout@v2
      - name: Build roswell:${{ matrix.version }}-${{ matrix.target }} image
        if: matrix.target == 'debian' || matrix.version != 'edge'
        run: ./build.sh roswell ${{ matrix.version }} ${{ matrix.target }}
      - name: Test roswell:${{ matrix.version }}-${{ matrix.target }} image
        if: matrix.target == 'debian' || matrix.version != 'edge'
        run: ./test.sh roswell ${{ matrix.version }} ${{ matrix.target }} ros
      - name: Publish roswell:${{ matrix.version }}-${{ matrix.target }} image
        if: github.ref == 'refs/heads/master' && (matrix.target == 'debian' || matrix.version != 'edge')
        env:
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: ./publish.sh roswell ${{ matrix.version }} ${{ matrix.target }}

  sbcl:
    name: SBCL
    runs-on: ubuntu-18.04
    needs: roswell
    strategy:
      matrix:
        target: [debian, ubuntu, alpine]
        version: ["1.3.20", "1.3.21", "1.4.0", "1.4.1", "1.4.2", "1.4.3", "1.4.4", "1.4.5", "1.4.6", "1.4.7", "1.4.8", "1.4.9", "1.4.10", "1.4.11", "1.4.12", "1.4.13", "1.4.14", "1.4.15", "1.4.16", "1.5.0", "1.5.1", "1.5.2", "1.5.3", "1.5.4", "1.5.5", "1.5.6", "1.5.7", "1.5.8", "1.5.9", "2.0.0"]

    steps:
      - uses: actions/checkout@v2
      - name: Build sbcl:${{ matrix.version }}-${{ matrix.target }} image
        run: ./build.sh sbcl ${{ matrix.version }} ${{ matrix.target }}
      - name: Test sbcl:${{ matrix.version }}-${{ matrix.target }} image
        run: ./test.sh sbcl ${{ matrix.version }} ${{ matrix.target }}
      - name: Publish sbcl:${{ matrix.version }}-${{ matrix.target }} image
        if: github.ref == 'refs/heads/master'
        env:
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: ./publish.sh sbcl ${{ matrix.version }} ${{ matrix.target }}

  ccl:
    name: Clozure CL
    runs-on: ubuntu-18.04
    needs: roswell
    strategy:
      matrix:
        target: [debian, ubuntu, alpine]
        version: ["1.10", "1.11", "1.11.5"]

    steps:
      - uses: actions/checkout@v2
      - name: Build ccl:${{ matrix.version }}-${{ matrix.target }} image
        run: ./build.sh ccl ${{ matrix.version }} ${{ matrix.target }}
      - name: Test ccl:${{ matrix.version }}-${{ matrix.target }} image
        run: ./test.sh ccl ${{ matrix.version }} ${{ matrix.target }}
      - name: Publish ccl:${{ matrix.version }}-${{ matrix.target }} image
        if: github.ref == 'refs/heads/master'
        env:
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: ./publish.sh ccl ${{ matrix.version }} ${{ matrix.target }}
